language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
install:
 - pip install argparse --use-mirrors
   # Install the dependencies the app itself has
   # which in this case I choose to keep in a requirements file
 - pip install -r requirements.txt --use-mirrors
   # Install whatever version of Django that's listed above
   # Travis is currently working on
 - pip install -q Django==$DJANGO_VERSION --use-mirrors
script: make test
