language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
install:
 - pip install -q Django==$DJANGO_VERSION --use-mirrors
script: make test
notifications:
    irc: "irc.freenode.org#loogica"
